name: CI Process

on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: ci-approval
    steps:
      - name: Run CI tasks
        run: echo "Running CI tasks like build and test"

