name: Hello World Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    environment: 
      name: ci-approval  # The name of the environment you created
    steps:
      - name: Hello World
        run: echo "Hello, World! Approved workflow run."
