name: Test Workflow

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_label:
    runs-on: ubuntu-latest
      if: ${{ github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'pull_request_target' &&
             (github.event.action != 'labeled' &&
              contains(github.event.pull_request.labels.*.name, 'run-ci') ||
              (github.event.action == 'labeled' &&
               github.event.label.name == 'run-ci'))) }}

